#include <stdlib.h>
#include <stdio.h>

/*
 * Header and SO location
 * /usr/include/libusb-1.0/libusb.h
 * /usr/lib64/libusb-1.0.so
 */
#include <libusb-1.0/libusb.h>

/* increase when device plugin in or out */
int plugin_in_out = 0;
libusb_device_handle *handle;

/* plugin handler */
static int LIBUSB_CALL plugin_handler(libusb_context *ctx, libusb_device *dev, libusb_hotplug_event event, void *user_data)
{
	struct libusb_device_descriptor desc;
	int rc;

	rc = libusb_get_device_descriptor(dev, &desc);
	if (LIBUSB_SUCCESS != rc)
		fprintf (stderr, "Error getting device descriptor\n");

	printf("Device attached: %04x:%04x\n", desc.idVendor, desc.idProduct);

	libusb_open(dev, &handle);

	plugin_in_out++;

	return 0;
}

/* plugout handler */
static int LIBUSB_CALL plugout_handler(libusb_context *ctx, libusb_device *dev, libusb_hotplug_event event, void *user_data)
{
	printf ("Device detached\n");

	libusb_close(handle);

	plugin_in_out++;

	return 0;
}

void print_usage(char *name)
{
	printf("%s vid pid\n", name);
	printf("%s 0x0000 0x0538\n", name);
}

int main(int argc, char *argv[])
{
	/*
	 * Generated by register callback, unique
	 * can be used to deregister callback
	 */
	libusb_hotplug_callback_handle handle_id[2];
	int pid, vid;
	int rc;

	if (argc < 2)
	{
		print_usage(argv[0]);
		return -1;
	}

	vid = strtol(argv[1], NULL, 0);
	pid = strtol(argv[2], NULL, 0);
	printf("vid = 0x%04x, pid = 0x%04x\n", vid, pid);

	/*
	 * Initialize libusb and create a default context
	 * If your application is guaranteed to only ever
	 * include a single libusb user (i.e. you),
	 * you do not have to worry about contexts:
	 * pass NULL in every function call where a context is required
	 * The default context will be used.
	 */
	rc = libusb_init(NULL);
	if (rc < 0)
	{
		printf("failed to initialise libusb: %s\n", libusb_error_name(rc));
		return EXIT_FAILURE;
	}

	/* Check at runtime if the loaded library has a given capability */
	if (!libusb_has_capability(LIBUSB_CAP_HAS_HOTPLUG))
	{
		printf ("Hotplug capabilites are not supported on this platform\n");
		libusb_exit (NULL);
		return EXIT_FAILURE;
	}

	/* Register the callback handler for plugin and is ready to use */
	rc = libusb_hotplug_register_callback(NULL, LIBUSB_HOTPLUG_EVENT_DEVICE_ARRIVED, 0, vid,
		pid, LIBUSB_HOTPLUG_MATCH_ANY, plugin_handler, NULL, &handle_id[0]);
	if (LIBUSB_SUCCESS != rc) {
		fprintf (stderr, "Error registering callback 0\n");
		libusb_exit (NULL);
		return EXIT_FAILURE;
	}

	/* Register the callback handler for device plugout */
	rc = libusb_hotplug_register_callback(NULL, LIBUSB_HOTPLUG_EVENT_DEVICE_LEFT, 0, vid,
		pid, LIBUSB_HOTPLUG_MATCH_ANY, plugout_handler, NULL, &handle_id[1]);
	if (LIBUSB_SUCCESS != rc) {
		fprintf (stderr, "Error registering callback 1\n");
		libusb_exit (NULL);
		return EXIT_FAILURE;
	}

	while (plugin_in_out < 2)
	{
		/* Handle and pending events, timeout at 60 seconds */
		rc = libusb_handle_events(NULL);
		if (rc < 0)
			printf("libusb_handle_events() failed: %s\n", libusb_error_name(rc));
	}

	/* deregister the callbacks */
	libusb_hotplug_deregister_callback(NULL, handle_id[0]);
	libusb_hotplug_deregister_callback(NULL, handle_id[1]);

	libusb_exit(NULL);

	return 0;
}
